language: java
branches:
  only:
    - develop
    - "/^release-[0-999].[0-999]$/"
    - master
notifications:
  email:
    recipients:
      - deimercode@gmail.com
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - gem install faraday -v 1.9.3
script:
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify
  - mvn verify sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=dhernandez04 -Dsonar.login=$SONAR
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU
  on:
    branch: master
  app: ecosystem-demo-miv